# cloudbuild.yaml
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA', '.']
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA']
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Adjust if authentication is required
      - '--set-env-vars=DATABASE_URL=postgresql://${_DB_USER}:${_DB_PASSWORD}@/${_DB_NAME}?host=/cloudsql/${_DB_CONNECTION_NAME}' # Example for Cloud SQL
      - '--set-env-vars=GCP_PROJECT_ID=${PROJECT_ID}'
      - '--set-env-vars=GCS_BUCKET_NAME=${_CLOUD_STORAGE_BUCKET_NAME}'
      - '--set-env-vars=NEXTAUTH_SECRET=${_NEXTAUTH_SECRET}'
      - '--set-env-vars=NEXT_PUBLIC_API_BASE_URL=https://${_SERVICE_NAME}-${_REGION}.run.app' # Cloud Run URL will be set by Cloud Build
      # Add other environment variables here as needed
    entrypoint: gcloud
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_REPO_NAME: 'docker-repo'
  _IMAGE_NAME: 'photo-spot-image'
  _SERVICE_NAME: 'photo-spot-app'
  _REGION: 'asia-northeast1'
  _CLOUD_STORAGE_BUCKET_NAME: 'your-gcs-bucket-name' # Replace with your GCS bucket name
  _NEXTAUTH_SECRET: 'your-nextauth-secret' # Replace with your NextAuth secret
  _DB_USER: 'your-db-user' # Replace with your DB user
  _DB_PASSWORD: 'your-db-password' # Replace with your DB password
  _DB_NAME: 'your-db-name' # Replace with your DB name
  _DB_CONNECTION_NAME: 'your-project-id:your-region:your-cloudsql-instance-name' # Replace with your Cloud SQL instance connection name
  _SERVICE_URL: 'https://photo-spot-app-xxxxxxxx-an.a.run.app' # Cloud Run URL, will be set by Cloud Build upon deployment
