# cloudbuild.yaml
steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:latest'
      - '--build-arg'
      - 'DATABASE_URL=postgresql://${_DB_USER}:${_DB_PASSWORD}@/${_DB_NAME}?host=/cloudsql/${_DB_CONNECTION_NAME}'
      - '--build-arg'
      - 'AUTH_SECRET=${_AUTH_SECRET}'
      - '--build-arg'
      - 'AUTH_GOOGLE_ID=${_AUTH_GOOGLE_ID}'
      - '--build-arg'
      - 'AUTH_GOOGLE_SECRET=${_AUTH_GOOGLE_SECRET}'
      - '--build-arg'
      - 'AUTH_URL=${_AUTH_URL}'
      - '--build-arg'
      - 'GCS_URL=${_GCS_URL}'
      - '--build-arg'
      - 'GCP_PROJECT_ID=${PROJECT_ID}'
      - '--build-arg'
      - 'GCS_BUCKET_NAME=${_CLOUD_STORAGE_BUCKET_NAME}'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_BASE_URL=${_NEXT_PUBLIC_API_BASE_URL}'
      - '.'
  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA']
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Adjust if authentication is required
    entrypoint: gcloud
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_AR_REPO_NAME}/${_IMAGE_NAME}:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _AR_REPO_NAME: 'docker-repo'
  _IMAGE_NAME: 'photo-spot-image'
  _SERVICE_NAME: 'photo-spot-app'
  _REGION: 'asia-northeast1'
  _CLOUD_STORAGE_BUCKET_NAME: 'photo-spot-image-bucket'
  _AUTH_SECRET: 'your-auth-secret'
  _AUTH_GOOGLE_ID: 'your-google-client-id'
  _AUTH_GOOGLE_SECRET: 'your-google-client-secret'
  _AUTH_URL: 'your-auth-url'
  _GCS_URL: 'https://storage.googleapis.com'
  _NEXT_PUBLIC_API_BASE_URL: 'http://localhost:3000' # Default value, override in trigger
